### ISSUE TITLE
Suggested improvement

### ISSUE THREAD

**Issue by houhc1** [Runisco/BunkrSorter#1]
Hi Runisco, 

I recently found your sorter. It works pretty good, but I noticed that things in the kilobyte range stayed at the top. I poked around and for that adding 
`sizeMultiplierDeterminer == "kB"`
to the IF statement at line 41 helped, but there were still kB at the beginning after sorting. So, I determined it might be better to convert everything to MB instead of whatever is going on with the sizeMultiplier. I update the script to have this replace the if statement that starts at line 41:
`        if (sizeMultiplierDeterminer == "KiB"){`
`            sizeMultiplier = (1/1024);`
`        } else if (sizeMultiplierDeterminer == "KB"){`
`            sizeMultiplier = (1/1024);`
`        } else if (sizeMultiplierDeterminer == "kB"){`
`            sizeMultiplier = (1/1024);`
`        } else if (sizeMultiplierDeterminer == "MiB"){`
`            sizeMultiplier = 1;`
`        } else if (sizeMultiplierDeterminer == "MB"){`
`            sizeMultiplier = 1;`
`        } else if (sizeMultiplierDeterminer == "GiB"){`
`            sizeMultiplier = 1024;`
`        } else if (sizeMultiplierDeterminer == "GB"){`
`            sizeMultiplier = 1024;`
`        }`
I found that perfectly sorted the albums.

**Comment by Runisco** [comment]
I had new values in my own test version, but yours must be much better, so I've added the values. Thank you.
