### ISSUE TITLE
Script does not work anymore

### ISSUE THREAD

**Issue by undercoverelk** [Runisco/BunkrSorter#3]
It seems like bunkr has changed it's layout in some way and in result the script doesn't show a "sort" button anymore.
I have some coding experience, but never worked with that kind of stuff so I wasn't able to fix it for myself.

**Comment by Runisco** [comment]
Have you made sure to open the raw file to update it? A fix went out yesterday for others with similar issues.

If it still doesn't work, please provide the bunkr url and a screenshot of what you see.

**Comment by undercoverelk** [comment]
Sorry, I didn't see the fix as I was using your script via sleazyfork. Thank you!
