### ISSUE TITLE
Stopped working.

### ISSUE THREAD

**Issue by nerdorican** [Runisco/BunkrSorter#4]
It just stopped working.

**Comment by Runisco** [comment]
gonna need a link

**Comment by nerdorican** [comment]
> gonna need a link

https://bunkr.la/a/DSv1iksZ

**Comment by Runisco** [comment]
Script is working correctly. Make sure you've updated your extension and the script by opening https://github.com/Runisco/BunkrSorter/raw/main/BunkrSorter.user.js and choose to install, reinstall, or update.
